apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
data:
  config.json: |
    {
      "environment" : "dev"
    }
# kubectl creates configmap example-config --from-file ./golang/configs/config.json
